In [1]:
import pandas as pd

df_A = pd.read_csv("matrixA_named.csv")
df_B = pd.read_csv("matrixB_named.csv")

In [2]:
df_A

,Unnamed: 0,X [m],Y [m],Z [m],Vx [m/s],Vy [m/s],Vz [m/s],Speed [m/s],Opening Angle [°],Roll Angle Left [°],Roll Angle Right [°],Yaw Angle Left [°],Yaw Angle Right [°],Stalling Angle Left [°],Stalling Angle Right [°]
0,X [m],1.001195,0.003460,0.001575,4.839262e-03,-0.011133,0.0,0.0,0.000402,-0.000141,-0.000138,-0.000036,0.000163,0.000292,0.000030
1,Y [m],0.000006,0.999432,0.000011,2.098365e-07,0.051714,0.0,0.0,0.000010,-0.000026,-0.000024,-0.000015,0.000010,0.000038,-0.000039
2,Z [m],-0.016565,-0.002964,0.980455,-7.500975e-04,0.007303,0.0,0.0,-0.000093,-0.000396,0.000398,0.000243,-0.000129,0.001282,0.001456
3,Vx [m/s],-0.024283,0.014536,-0.035197,9.999995e-01,-0.059806,0.0,0.0,0.006940,0.003441,-0.005286,-0.004509,0.006616,-0.009815,-0.010043
4,Vy [m/s],-0.001865,0.069446,-0.002704,1.086692e-05,0.757103,0.0,0.0,0.001992,-0.002818,-0.002936,0.001790,0.003856,0.000869,-0.001694
5,Vz [m/s],0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Speed [m/s],0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Opening Angle [°],-0.035293,-0.018812,-0.043980,9.572362e-03,0.022079,0.0,0.0,0.464707,-0.008612,-0.001274,0.022188,-0.014890,0.011442,0.010047
8,Roll Angle Left [°],-0.015047,-0.050277,-0.008944,6.165663e-03,0.295007,0.0,0.0,-0.007410,0.487194,-0.004111,0.003049,-0.011174,0.042025,-0.012650
9,Roll Angle Right [°],-0.000360,-0.035908,-0.014076,-4.834316e-03,0.238053,0.0,0.0,0.014376,-0.000335,0.491242,-0.021135,0.005011,0.001257,-0.033420
10,Yaw Angle Left [°],-0.012890,-0.002378,-0.014221,4.639826e-03,-0.011329,0.0,0.0,-0.017360,-0.005529,-0.001154,0.509636,-0.006137,0.008307,0.003540
11,Yaw Angle Right [°],0.016420,0.014504,0.019824,-4.887915e-03,-0.041963,0.0,0.0,0.017975,0.003596,0.000601,-0.010864,0.505954,-0.005094,-0.007157
12,Stalling Angle Left [°],-0.031316,-0.013058,-0.037355,6.550785e-03,0.052637,0.0,0.0,-0.017346,-0.004656,-0.005915,0.004441,-0.000488,0.502353,-0.005716
13,Stalling Angle Right [°],-0.031156,0.002848,-0.038230,5.944336e-03,0.028426,0.0,0.0,-0.016584,0.001817,-0.000512,0.003239,-0.001408,0.001817,0.495578

V matriki A lahko opazimo:
- hitrost v navpični smeri in celotna hitrost na sam skok ne vplivata. sta popolnoma neodvisni od ostalih meritev.
- po diagonali imamo:
    - približno 1 za x, y, z, vx -> vy je suspiciously low
    - 0 (kot vse ostalo) za vz, speed
    - približno 0.5 za vse kote

Problemi: 
- kako je Vz neodvisen od Vz...it should be at least 1. enako za speed
- vx od x bi moral biti okoli 0.5

Gpt opinion:
- you should be worried, but not about the model, the data itself seems faulty.

In [3]:
df_B

,Unnamed: 0,takeoff_Speed,mid_Speed,landing_Speed,takeoff_Tangent,mid_Tangent,landing_Tangent,takeoff_Cross,mid_Cross,landing_Cross,...,mid_Turbulence_quad,landing_Turbulence_quad,Speed [m/s],Opening Angle [°],Roll Angle Left [°],Roll Angle Right [°],Yaw Angle Left [°],Yaw Angle Right [°],Stalling Angle Left [°],Stalling Angle Right [°]
0,X [m],0.000198,-0.005566,-0.008501,0.003752,-0.000532,-0.001648,-0.017247,0.008492,0.007606,...,0.086208,0.001615,0.0,0.000416,-0.000127,-0.000149,-0.000035,0.000175,0.000295,0.000031
1,Y [m],0.000691,-0.000188,-0.000354,-0.000213,-0.000015,0.000054,0.000288,0.000034,-0.000092,...,-0.000388,-0.000308,0.0,0.000010,-0.000026,-0.000024,-0.000015,0.000010,0.000038,-0.000039
2,Z [m],0.009544,0.039907,0.028126,0.005841,0.001902,0.008122,0.081289,-0.052729,-0.010069,...,-0.051860,-0.055530,0.0,-0.000097,-0.000393,0.000410,0.000246,-0.000129,0.001284,0.001455
3,Vx [m/s],0.016365,0.006336,-0.125503,0.048009,-0.035130,-0.033472,0.065189,0.054817,0.009638,...,0.161486,-0.156319,0.0,0.006902,0.003487,-0.005215,-0.004530,0.006594,-0.009816,-0.010037
4,Vy [m/s],0.006735,0.053971,-0.041423,0.006428,-0.006590,-0.018902,-0.120802,-0.077409,0.030851,...,-0.032055,0.059623,0.0,0.001992,-0.002818,-0.002936,0.001790,0.003856,0.000869,-0.001694
5,Vz [m/s],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,Speed [m/s],0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,Opening Angle [°],-0.136811,0.051949,0.353630,0.045258,-0.099990,0.086450,0.172087,-0.117351,-0.361015,...,-0.789513,1.035705,0.0,0.464710,-0.008622,-0.001278,0.022184,-0.014886,0.011442,0.010047
8,Roll Angle Left [°],-0.315202,0.088050,0.052272,0.078515,-0.079224,0.108911,0.483422,-0.118314,-0.465758,...,0.280400,-0.767358,0.0,-0.007406,0.487192,-0.004110,0.003047,-0.011172,0.042024,-0.012650
9,Roll Angle Right [°],0.594491,0.057293,-0.575957,-0.159062,0.053205,-0.042876,-0.261166,0.134531,0.304939,...,0.033042,-0.217546,0.0,0.014370,-0.000334,0.491246,-0.021141,0.005006,0.001257,-0.033420
10,Yaw Angle Left [°],-0.050949,0.057955,0.266499,0.031990,-0.028108,0.027737,0.139305,-0.093912,-0.159829,...,-0.137165,0.746852,0.0,-0.017364,-0.005528,-0.001157,0.509637,-0.006139,0.008307,0.003540
11,Yaw Angle Right [°],0.095329,0.046382,-0.140045,-0.024093,0.068218,-0.056166,-0.070678,0.020359,0.195972,...,0.766131,0.485080,0.0,0.017972,0.003599,0.000596,-0.010862,0.505954,-0.005094,-0.007157
12,Stalling Angle Left [°],0.008580,-0.114088,0.041801,-0.022914,-0.055343,0.053878,0.026730,-0.056804,-0.145660,...,-0.657503,-0.820074,0.0,-0.017345,-0.004656,-0.005915,0.004441,-0.000488,0.502353,-0.005716
13,Stalling Angle Right [°],-0.136258,-0.026948,0.099563,0.017676,-0.051750,0.039031,0.183884,-0.087403,-0.139541,...,-0.778004,-0.121531,0.0,-0.016583,0.001817,-0.000512,0.003239,-0.001408,0.001817,0.495578

- vx, vy in koti so vsi precej odvisni od turbulence
- opening angle je močno odvisen od turbulence in faktorjev ob pristajanju
- koti po diagonali imajo sami s sabo podobno 0.5 kot pti A matriki
- hitrost ima same ničle
- landing turbulenca je zelo odvisna od vseh kotov
- korelacija x, y, z je zelo enakomerna pri features
    -turbulenca ima največji vpliv na vse, zelo visok vpliv na x in dokaj visok vpliv na z koordinato, vendar nekoliko nižji na y

problemi so podobni kot prej

gpt opinion ni bil nič pametnega